### ISSUE TITLE
When attempting to use the turtle claw on a server throws a error in the turtle.

### ISSUE THREAD

**Issue by Blitzsy** [KnightMiner/KnightPeripherals#1]
Thrown error: http://pastebin.com/4y1Z07eE
Screenshot of error: http://i.imgur.com/aDnJUUV.png
Code that caused the error: http://pastebin.com/rAXP4wTZ
Mods List: http://pastebin.com/wsPG70FX

**Comment by KnightMiner** [comment]
Hmm, apparently the Vector3f class is a client side only class used for rendeing, whoopsy. I'll have a fix up as soon as I finish testing it.

**Comment by KnightMiner** [comment]
And fixed. You can download the fixed version [here](/KnightMiner/KnightPeripherals/releases/tag/v1.1.1) or from Curse
