### ISSUE TITLE
Attempting to unequip the hammer from the turtle causes the item to be lost.

### ISSUE THREAD

**Issue by Blitzsy** [KnightMiner/KnightPeripherals#2]
This happens in singleplayer and multiplayer and doesn't matter which side the turtle equip/unequips the hammer.

Code that caused the bug: http://pastebin.com/N3hRwiSG
Mods List: http://pastebin.com/y28b8whM

**Comment by KnightMiner** [comment]
Hmm, I wonder if this has something to do with me using `GameRegistry.findItemStack` rather than creating the itemstack with `GameRegisty.findItem`

**Comment by KnightMiner** [comment]
Nope, nevermind. The issue is I was dumb. The turtle is crafted using an itemstack with a size of 0, instead of 1, meaning it equips fine but unequips an empty stack
