### ISSUE TITLE
1.7.10 Click turtle

### ISSUE THREAD

**Issue by BaxAndrei** [KnightMiner/KnightPeripherals#6]
http://prntscr.com/maskyu
http://prntscr.com/masl41
How should I make it work?

**Comment by KnightMiner** [comment]
You have to wrap the peripheral like any other peripheral. See [the wiki page](https://github.com/KnightMiner/KnightPeripherals/wiki/Clicking-Turtle)

**Comment by BaxAndrei** [comment]
http://prntscr.com/mb890r
http://prntscr.com/mb89ht
http://prntscr.com/mb89ny

```
local culegere = peripheral.wrap("down")
local randuri = 2
-- randuri = randuri * 2 (EX: randuri = 1 > 2)
local campuri = 9

turtle.select(1)

for iranduri=1,randuri,1 do
 
  for icampuria=1,campuri,1 do
    turtle.forward()
    culegere.clickDown()
  end

  turtle.turnRight()
  turtle.forward()
  turtle.turnRight()

  for icampurib=1,campuri,1 do
    turtle.forward()
    culegere.clickDown()
  end
  
  turtle.turnLeft()
  turtle.forward()
  turtle.turnLeft()
end

local inapoi = randuri*2

turtle.turnLeft()

for iinapoi=1,inapoi,1 do
  turtle.forward()
end

turtle.turnRight()

```

http://prntscr.com/mb8cas

**Comment by KnightMiner** [comment]
You have the wrong peripheral side, you put the claw on the right but are wrapping down.

**Comment by BaxAndrei** [comment]
`You can only equip items either to the left or right sides`, so I can`t use this to right click agricraft crops

**Comment by KnightMiner** [comment]
No? The side the peripheral is on has nothing to do with the sodes you can click. You can use peripheral.wrap("right") and clockDown.

**Comment by BaxAndrei** [comment]
ok, thanx
